name: parabeac_core
description: Continuous Design / Continuous Integration for Figma-to-Flutter

version: 4.0.0
homepage: https://www.parabeac.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.4.2
  archive: ^3.4.10
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  mockito: ^5.4.2
  hex: ^0.2.0
  build: ^2.3.1
  logger: ^2.1.0
  uuid: ^4.3.3
  quick_log: ^5.3.0
  http2: ^2.0.1
  recase: ^4.1.0
  tuple: ^2.0.2
  path: ^1.8.3
  file: ^6.1.4
  get_it: ^7.6.0
  # pbdl:
  #   git:
  #     url: https://github.com/Parabeac/pbdl.git
  #     ref: master
  pbdl: 
    path: ./pbdl
  #directed_graph: ^0.3.9
  directed_graph: 
    path: ./directed_graph
  sentry: ^7.18.0
  yaml_modify: ^1.0.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.3
  build_config: ^1.1.1

dependency_overrides:
  uuid: ^4.2.2