name: directed_graph

description: Directed graph with algorithms enabling topological ordering and
  sorting of vertices. The package provides a graph crawler for finding 
  paths connecting two vertices.

version: 0.2.3

homepage: https://github.com/simphotonics/directed_graph

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  graphs: ^2.2.0
  lazy_evaluation: ^1.1.0
  meta: ^1.12.0

dev_dependencies:
  ansicolor: ^2.0.1
  benchmark_harness: ^2.2.1
  pedantic: ^1.11.1
  test: ^1.21.4
